"""P13 operator retry boundary over isolated SQLite work items."""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
import json
import sqlite3
from pathlib import Path

import pytest

from scope_recall.contracts import ContractError, InstanceBinding, TrustedContext
from scope_recall.core import CoreConfig, MemoryCore
from scope_recall.runtime.instance import RuntimeInstanceConfig, build_runtime_instance
from scope_recall.runtime.worker_entry import run_retry_failed
from v11_support import source_event


def _binding(root: Path, *, name: str = "TEST-p13-installation") -> InstanceBinding:
    return InstanceBinding("TEST-p13-agent", name, root, frozenset({"TEST-p13-scope"}), True)


def _context(binding: InstanceBinding, session: str = "TEST-p13-session") -> TrustedContext:
    return TrustedContext(binding, session, binding.scope_ids, "human_direct")


def _fail_three_times(core: MemoryCore, context: TrustedContext, work_id: int) -> None:
    # Source capture timestamps are generated by the fixture clock; use a
    # safely future maintenance clock so backoff/availability is deterministic.
    base = datetime(2099, 9, 6, tzinfo=timezone.utc)
    for index in range(3):
        now = (base + timedelta(hours=index)).isoformat().replace("+00:00", "Z")
        with core.storage.write(context) as tx:
            claimed = tx.work.claim_next(
                "TEST-p13-failer", now, lease_seconds=60.0, limit=32
            )
            target = next(value for value in claimed if value.work_id == work_id)
            for item in claimed:
                mutation = tx.work.fail(
                    item.work_id,
                    item.lease_token,
                    item.lease_owner,
                    error_code="model_unavailable",
                    now=now,
                    recoverable=True,
                )
                if item.work_id == target.work_id:
                    if index < 2:
                        assert mutation.state == "pending"
                    else:
                        assert mutation.state == "failed"


def _failed_embed(tmp_path: Path):
    binding = _binding(tmp_path / "data")
    core = MemoryCore(CoreConfig(binding))
    core.initialize()
    context = _context(binding)
    result = core.record_event(
        context,
        source_event(
            source_event_key="TEST-p13/operator-retry",
            content="forget this P13 synthetic source for explicit operator retry.",
        ),
        scope_id="TEST-p13-scope",
        remaining_seconds=10,
    )
    ref = result.event_refs[0].ref
    with sqlite3.connect(core.storage.path) as conn:
        work_id = conn.execute(
            "SELECT work_id FROM work_items WHERE work_type='embed' AND subject_ref=?",
            (ref,),
        ).fetchone()[0]
    _fail_three_times(core, context, work_id)
    return binding, core, context, work_id, ref


def test_operator_retry_requeues_only_named_failed_work_and_is_idempotent(tmp_path):
    binding, core, context, work_id, _ = _failed_embed(tmp_path)
    instance = build_runtime_instance(
        RuntimeInstanceConfig(binding=binding, session_id=context.session_id, allowed_scope_ids=binding.scope_ids)
    )
    try:
        first = instance.retry_failed((work_id,), operation_id="TEST-p13-op-1")
        assert first[0].disposition == "requeued"
        with core.storage.read(context) as tx:
            assert tx.work.read_state(work_id) == "pending"
        second = instance.retry_failed((work_id,), operation_id="TEST-p13-op-1")
        assert second[0].disposition == "already_pending"
    finally:
        instance.close()


def test_operator_retry_rejects_leased_deleted_and_stale_items(tmp_path):
    binding, core, context, work_id, ref = _failed_embed(tmp_path / "deleted")
    # A failed item cannot be revived after its source has been blocked by the
    # normal Core deletion operation; no SQL reset is used here.
    core.forget(
        context,
        {"protocol_version": "1.1", "mode": "delete", "target_refs": [ref], "expected_revisions": {ref: 1}},
        remaining_seconds=10,
    )
    with core.storage.write(context) as tx:
        result = tx.work.operator_retry_failed((work_id,), now="2026-09-06T01:00:00Z", operation_id="TEST-p13-deleted")
    assert result[0].disposition == "rejected"
    assert result[0].reason in {"source_deleted_or_inaccessible", "source_revision_stale"}

    binding2, core2, context2, work2, ref2 = _failed_embed(tmp_path / "leased")
    with core2.storage.write(context2) as tx:
        requeued = tx.work.operator_retry_failed(
            (work2,), now="2026-09-06T02:00:00Z", operation_id="TEST-p13-before-lease"
        )
        assert requeued[0].disposition == "requeued"
    with core2.storage.write(context2) as tx:
        claimed = tx.work.claim_next("TEST-p13-holder", "2026-09-06T02:00:00Z", lease_seconds=60, limit=1)
        assert claimed and claimed[0].work_id == work2
    with core2.storage.write(context2) as tx:
        result = tx.work.operator_retry_failed((work2,), now="2026-09-06T02:00:01Z", operation_id="TEST-p13-leased")
    assert result[0].reason == "leased"

    binding3, core3, context3, work3, ref3 = _failed_embed(tmp_path / "stale")
    newer = core3.record_event(
        context3,
        source_event(source_event_key="TEST-p13/operator-retry", content="newer revision", source_revision=2),
        scope_id="TEST-p13-scope",
        remaining_seconds=10,
    )
    assert newer.event_refs[0].ref == ref3
    with core3.storage.write(context3) as tx:
        result = tx.work.operator_retry_failed((work3,), now="2026-09-06T03:00:00Z", operation_id="TEST-p13-stale")
    assert result[0].reason == "source_revision_stale"


def test_operator_retry_checks_expected_epoch_and_finite_request(tmp_path):
    binding, core, context, work_id, _ = _failed_embed(tmp_path)
    with core.storage.read(context) as tx:
        epoch = tx.status().memory_epoch
    with core.storage.write(context) as tx:
        with pytest.raises(ContractError, match="VERSION_CONFLICT"):
            tx.work.operator_retry_failed(
                (work_id,), now="2026-09-06T04:00:00Z", operation_id="TEST-p13-epoch", expected_memory_epoch=epoch - 1
            )
    with core.storage.write(context) as tx:
        with pytest.raises(ContractError, match="retry_budget"):
            tx.work.operator_retry_failed(
                tuple(range(1, 10)), now="2026-09-06T04:00:00Z", operation_id="TEST-p13-too-many"
            )


def test_operator_retry_rejects_work_outside_trusted_allowed_scopes(tmp_path):
    binding = InstanceBinding(
        "TEST-p13-agent", "TEST-p13-installation", tmp_path / "data",
        frozenset({"TEST-p13-scope-a", "TEST-p13-scope-b"}), True,
    )
    core = MemoryCore(CoreConfig(binding))
    core.initialize()
    all_context = TrustedContext(binding, "TEST-p13-all", binding.scope_ids, "human_direct")
    result = core.record_event(
        all_context,
        source_event(source_event_key="TEST-p13/foreign", content="forget foreign scope source."),
        scope_id="TEST-p13-scope-b",
        remaining_seconds=10,
    )
    ref = result.event_refs[0].ref
    with sqlite3.connect(core.storage.path) as conn:
        work_id = conn.execute(
            "SELECT work_id FROM work_items WHERE work_type='embed' AND subject_ref=?", (ref,)
        ).fetchone()[0]
    _fail_three_times(core, all_context, work_id)
    restricted = TrustedContext(binding, "TEST-p13-restricted", frozenset({"TEST-p13-scope-a"}), "human_direct")
    with core.storage.write(restricted) as tx:
        result = tx.work.operator_retry_failed(
            (work_id,), now="2099-09-06T05:00:00Z", operation_id="TEST-p13-foreign"
        )
    assert result[0].disposition == "rejected"
    assert result[0].reason == "scope_denied"


def test_operator_retry_rejects_untrusted_origins_without_state_change(tmp_path):
    binding, core, context, work_id, _ = _failed_embed(tmp_path)
    untrusted = TrustedContext(binding, context.session_id, binding.scope_ids, "origin_unknown")
    with core.storage.write(untrusted) as tx:
        with pytest.raises(ContractError, match="operator_origin"):
            tx.work.operator_retry_failed(
                (work_id,), now="2099-09-06T05:30:00Z", operation_id="TEST-p13-untrusted"
            )
    with core.storage.read(context) as tx:
        assert tx.work.read_state(work_id) == "failed"

    normal_instance = build_runtime_instance(
        RuntimeInstanceConfig(
            binding=binding,
            session_id=context.session_id,
            allowed_scope_ids=binding.scope_ids,
        )
    )
    try:
        with pytest.raises(ContractError, match="operator_origin"):
            normal_instance.retry_failed(
                (work_id,), operation_id="TEST-p13-runtime-untrusted", operator_context=untrusted
            )
    finally:
        normal_instance.close()

    external_instance = build_runtime_instance(
        RuntimeInstanceConfig(
            binding=binding,
            session_id=context.session_id,
            allowed_scope_ids=binding.scope_ids,
            actor_origin="external_document",
        )
    )
    try:
        with pytest.raises(ContractError, match="operator_origin"):
            external_instance.retry_failed((work_id,), operation_id="TEST-p13-external")
    finally:
        external_instance.close()
    with core.storage.read(context) as tx:
        assert tx.work.read_state(work_id) == "failed"


def test_operator_retry_has_two_explicit_cycles_then_stops(tmp_path):
    binding, core, context, work_id, _ = _failed_embed(tmp_path)
    with core.storage.write(context) as tx:
        assert tx.work.operator_retry_failed(
            (work_id,), now="2099-09-06T06:00:00Z", operation_id="TEST-p13-cycle-1"
        )[0].disposition == "requeued"
    for index in (1, 2):
        with core.storage.write(context) as tx:
            claimed = tx.work.claim_next(
                "TEST-p13-cycle-worker", f"2099-09-06T0{6 + index}:00:00Z", lease_seconds=60, limit=1
            )
            assert claimed and claimed[0].work_id == work_id
            tx.work.fail(
                work_id, claimed[0].lease_token, claimed[0].lease_owner,
                error_code="model_unavailable", now=f"2099-09-06T0{6 + index}:00:01Z", recoverable=True,
            )
        if index == 1:
            with core.storage.write(context) as tx:
                assert tx.work.operator_retry_failed(
                    (work_id,), now="2099-09-06T08:00:00Z", operation_id="TEST-p13-cycle-2"
                )[0].disposition == "requeued"
    with core.storage.write(context) as tx:
        result = tx.work.operator_retry_failed(
            (work_id,), now="2099-09-06T09:00:00Z", operation_id="TEST-p13-cycle-3"
        )
    assert result[0].reason == "operator_retry_budget"


def test_operator_retry_operation_tokens_are_exact_and_bounded(tmp_path):
    binding, core, context, work_id, _ = _failed_embed(tmp_path)
    with core.storage.write(context) as tx:
        assert tx.work.operator_retry_failed(
            (work_id,), now="2099-09-06T10:00:00Z", operation_id="TEST-p13-op-1"
        )[0].disposition == "requeued"
    with core.storage.write(context) as tx:
        claimed = tx.work.claim_next("TEST-p13-token-worker", "2099-09-06T10:00:01Z", lease_seconds=60, limit=1)
        assert claimed and claimed[0].work_id == work_id
        tx.work.fail(
            work_id, claimed[0].lease_token, claimed[0].lease_owner,
            error_code="model_unavailable", now="2099-09-06T10:00:02Z", recoverable=True,
        )
    with core.storage.write(context) as tx:
        # op-10 must not be confused with the earlier exact op-1 token.
        assert tx.work.operator_retry_failed(
            (work_id,), now="2099-09-06T11:00:00Z", operation_id="TEST-p13-op-10"
        )[0].disposition == "requeued"
        with pytest.raises(ContractError, match="retry_operation"):
            tx.work.operator_retry_failed(
                (work_id,), now="2099-09-06T11:00:00Z", operation_id="operator_retry:forged"
            )


def test_operator_retry_preserves_marker_when_failed_item_was_not_attempt_exhausted(tmp_path):
    binding = _binding(tmp_path / "data")
    core = MemoryCore(CoreConfig(binding))
    core.initialize()
    context = _context(binding)
    recorded = core.record_event(
        context,
        source_event(source_event_key="TEST-p13/nonrecoverable", content="forget nonrecoverable source."),
        scope_id="TEST-p13-scope",
        remaining_seconds=10,
    )
    ref = recorded.event_refs[0].ref
    with sqlite3.connect(core.storage.path) as conn:
        work_id = conn.execute(
            "SELECT work_id FROM work_items WHERE work_type='embed' AND subject_ref=?", (ref,)
        ).fetchone()[0]
    with core.storage.write(context) as tx:
        claimed = tx.work.claim_next("TEST-p13-initial-failure", "2099-09-06T12:00:00Z", lease_seconds=60, limit=32)
        target = next(item for item in claimed if item.work_id == work_id)
        for item in claimed:
            mutation = tx.work.fail(
                item.work_id, item.lease_token, item.lease_owner,
                error_code="derivation_invalid", now="2099-09-06T12:00:01Z", recoverable=False,
            )
            if item.work_id == target.work_id:
                assert mutation.state == "failed"
        assert tx.work.operator_retry_failed(
            (work_id,), now="2099-09-06T12:00:02Z", operation_id="TEST-p13-extra-1"
        )[0].disposition == "requeued"
    with core.storage.write(context) as tx:
        claimed = tx.work.claim_next("TEST-p13-extra-worker", "2099-09-06T12:00:03Z", lease_seconds=60, limit=32)
        target = next(item for item in claimed if item.work_id == work_id)
        for item in claimed:
            mutation = tx.work.fail(
                item.work_id, item.lease_token, item.lease_owner,
                error_code="model_unavailable", now="2099-09-06T12:00:04Z", recoverable=True,
            )
            if item.work_id == target.work_id:
                assert mutation.state == "pending"
        marker = tx._check().execute("SELECT last_error_code FROM work_items WHERE work_id=?", (work_id,)).fetchone()[0]
        assert marker.startswith("operator_retry:TEST-p13-extra-1|")


def test_worker_entry_retry_is_explicit_and_audited(tmp_path, capsys):
    binding, core, context, work_id, _ = _failed_embed(tmp_path)
    payload = {
        "binding": {
            "agent_id": binding.agent_id,
            "installation_id": binding.installation_id,
            "data_directory": str(binding.data_directory),
            "scope_ids": sorted(binding.scope_ids),
            "test_mode": True,
        },
        "session_id": context.session_id,
        "allowed_scope_ids": sorted(binding.scope_ids),
        "owner_id": "TEST-p13-worker",
        "request_seconds": 5.0,
        "drain_seconds": 5.0,
        "max_items": 1,
        "lease_seconds": 5.0,
        "auxiliary": {"external_embedding": False, "external_consolidation": False},
    }
    config_path = tmp_path / "worker.json"
    config_path.write_text(json.dumps(payload), encoding="utf-8")
    from io import StringIO

    output = StringIO()
    assert run_retry_failed(config_path, (work_id,), operation_id="TEST-p13-cli", output=output) == 0
    receipt = json.loads(output.getvalue())
    assert receipt["operator_retry"][0]["disposition"] == "requeued"
    assert receipt["operator_retry"][0]["operation_id"] == "TEST-p13-cli"
    assert receipt["processed"] == 0
    # Missing embedding capability waits without spending another attempt.
    assert "embed" in receipt["unavailable_work_types"]
    with sqlite3.connect(core.storage.path) as conn:
        marker = conn.execute("SELECT last_error_code FROM work_items WHERE work_id=?", (work_id,)).fetchone()[0]
    assert marker.startswith("operator_retry:TEST-p13-cli")
    output2 = StringIO()
    assert run_retry_failed(config_path, (work_id,), operation_id="TEST-p13-cli", output=output2) == 0
    receipt2 = json.loads(output2.getvalue())
    assert receipt2["operator_retry"][0]["disposition"] == "already_pending"
